---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: smartpoli-monitoring
    app.kubernetes.io/part-of: smartpoli-platform
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: observability
    environment: shared
    purpose: monitoring
    team: platform-team
    security-level: medium
---
# Resource Quota for Monitoring - Optimized for small VPS
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
  labels:
    app.kubernetes.io/name: smartpoli-monitoring
    app.kubernetes.io/part-of: smartpoli-platform
    environment: shared
spec:
  hard:
    requests.cpu: "500m"     # 0.5 CPU cores
    requests.memory: 1Gi     # 1GB RAM
    limits.cpu: "1"          # Max 1 CPU cores
    limits.memory: 2Gi       # Max 2GB RAM
    persistentvolumeclaims: "2"
    pods: "4"                # Prometheus, Grafana, etc.
    services: "3"
    secrets: "5"
    configmaps: "8"
---
# RBAC for Monitoring Admins
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-admin-sa
  namespace: monitoring
  labels:
    app.kubernetes.io/name: smartpoli-monitoring
    app.kubernetes.io/part-of: smartpoli-platform
    environment: shared
---
# Role for managing monitoring components
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-admin-role
  namespace: monitoring
  labels:
    app.kubernetes.io/name: smartpoli-monitoring
    app.kubernetes.io/part-of: smartpoli-platform
    environment: shared
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps", "secrets", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-admin-rolebinding
  namespace: monitoring
  labels:
    app.kubernetes.io/name: smartpoli-monitoring
    app.kubernetes.io/part-of: smartpoli-platform
    environment: shared
subjects:
- kind: ServiceAccount
  name: monitoring-admin-sa
  namespace: monitoring
- kind: Group
  name: platform-admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: monitoring-admin-role
  apiGroup: rbac.authorization.k8s.io
---
# ClusterRole for metrics collection across namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-cluster-role
  labels:
    app.kubernetes.io/name: smartpoli-monitoring
    app.kubernetes.io/part-of: smartpoli-platform
    environment: shared
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-cluster-rolebinding
  labels:
    app.kubernetes.io/name: smartpoli-monitoring
    app.kubernetes.io/part-of: smartpoli-platform
    environment: shared
subjects:
- kind: ServiceAccount
  name: monitoring-admin-sa
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: prometheus-cluster-role
  apiGroup: rbac.authorization.k8s.io
