---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: smartpoli-dev
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-dev
    app.kubernetes.io/version: "6.2.6"
    app.kubernetes.io/part-of: smartpoli-platform
    app.kubernetes.io/component: cache
    environment: dev
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
    appendonly yes
    appendfsync everysec
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: smartpoli-dev
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-dev
    app.kubernetes.io/version: "6.2.6"
    app.kubernetes.io/part-of: smartpoli-platform
    app.kubernetes.io/component: cache
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: redis-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: redis-dev
        app.kubernetes.io/version: "6.2.6"
        app.kubernetes.io/part-of: smartpoli-platform
        app.kubernetes.io/component: cache
        environment: dev
    spec:
      containers:
      - name: redis
        image: redis:6.2.6-alpine
        command:
          - redis-server
          - "/etc/redis/redis.conf"
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
          items:
          - key: redis.conf
            path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: smartpoli-dev
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-dev
    app.kubernetes.io/version: "6.2.6"
    app.kubernetes.io/part-of: smartpoli-platform
    app.kubernetes.io/component: cache
    environment: dev
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-dev
