---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: smartpoli-dev
  labels:
    app.kubernetes.io/name: django-api
    app.kubernetes.io/instance: django-api-dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: smartpoli-platform
    app.kubernetes.io/component: backend
    environment: dev
data:
  DJANGO_SETTINGS_MODULE: "smartpoli.settings.dev"
  DJANGO_ALLOWED_HOSTS: "django-api,localhost,127.0.0.1"
  DATABASE_URL: "postgres://smartpoli_user:Dev_Password_123@postgresql:5432/smartpoli_dev"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/1"
  CELERY_RESULT_BACKEND: "redis://redis:6379/2"
  DEBUG: "True"
  PYTHONUNBUFFERED: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: smartpoli-dev
  labels:
    app.kubernetes.io/name: django-api
    app.kubernetes.io/instance: django-api-dev
    app.kubernetes.io/part-of: smartpoli-platform
    app.kubernetes.io/component: backend
    environment: dev
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "django-insecure-dev-5%jq6j3_qn!=xy#s6q^15z4xv5$jj9hy-c16$bps6)qpd$z"
  ADMIN_USER: "admin"
  ADMIN_PASSWORD: "adminpass123"
  ADMIN_EMAIL: "admin@smartpoli.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
  namespace: smartpoli-dev
  labels:
    app.kubernetes.io/name: django-api
    app.kubernetes.io/instance: django-api-dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: smartpoli-platform
    app.kubernetes.io/component: backend
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: django-api
      app.kubernetes.io/instance: django-api-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django-api
        app.kubernetes.io/instance: django-api-dev
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/part-of: smartpoli-platform
        app.kubernetes.io/component: backend
        environment: dev
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.34
        command: ['sh', '-c', 'until nc -z postgresql 5432; do echo waiting for postgresql; sleep 2; done;']
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
      - name: migrations
        image: python:3.10-slim
        command: ['sh', '-c', 'pip install -U pip && pip install django psycopg2-binary && python manage.py migrate']
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: django-config
        - secretRef:
            name: django-secrets
      containers:
      - name: django-api
        image: python:3.10-slim
        command: ['sh', '-c', 'pip install -U pip && pip install django djangorestframework psycopg2-binary redis celery gunicorn && gunicorn smartpoli.wsgi:application --bind 0.0.0.0:8000']
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: django-config
        - secretRef:
            name: django-secrets
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /admin/login/
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /admin/login/
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: django-api
  namespace: smartpoli-dev
  labels:
    app.kubernetes.io/name: django-api
    app.kubernetes.io/instance: django-api-dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: smartpoli-platform
    app.kubernetes.io/component: backend
    environment: dev
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: django-api
    app.kubernetes.io/instance: django-api-dev
